# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deposit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class deposit(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 171)
        MainWindow.setStyleSheet("background-color: rgb(18, 18, 18);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(330, 50, 131, 51))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Fredoka One \";\n"
"border: 2px solid rgb(160,160,160);\n"
"padding: 5px;\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"   \n"
"    background-color: rgb(0, 85, 255);\n"
"    \n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 50, 311, 51))
        self.lineEdit_5.setToolTipDuration(-1)
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"       font: 18pt \"Fredoka One Light\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(160,160,160);\n"
"    padding: 5px;\n"
"    selection-color: rgb(0, 0, 255);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(0, 153, 188);\n"
"}\n"
"")
        self.lineEdit_5.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_5.setObjectName("lineEdit_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 470, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_7.setText(_translate("MainWindow", "Deposit"))
        self.lineEdit_5.setToolTip(_translate("MainWindow", "<html><head/><body><p>hi????</p></body></html>"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Enter Amount to deposit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = deposit()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
