# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from main import mainwin
import mysql.connector as sql

mycon= sql.connect(host="localhost",user="root",password="jehan26122003",database="bank")
mycur= mycon.cursor()

class Ui_MainWindow2(object):
    def openWindow2(self):
        
        self.window = QtWidgets.QMainWindow()
        self.ui = mainwin()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(622, 475)
        MainWindow2.setStyleSheet("background-color: rgb(18, 18, 18);")
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(16, 0, 591, 41))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"Fredoka One\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Fredoka One")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Fredoka One\";")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 91, 41))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 13pt \"Fredoka One\";")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(320, 70, 101, 41))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 9pt \"Fredoka One\";")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 230, 91, 41))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Fredoka One\";")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 310, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Fredoka One")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Fredoka One\";")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(320, 150, 101, 41))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Fredoka One\";")
        self.label_7.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(320, 230, 101, 41))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Fredoka One\";")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(320, 310, 101, 41))
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Fredoka One\";")
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(440, 150, 171, 41))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border-radius: 20px;\n"
"       font: 14pt \"Fredoka One Light\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(160,160,160);\n"
"    padding: 5px;\n"
"    selection-color: rgb(0, 0, 255);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(0, 153, 188);\n"
"}\n"
"")
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(440, 230, 171, 41))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    border-radius: 20px;\n"
"       font: 14pt \"Fredoka One Light\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(160,160,160);\n"
"    padding: 5px;\n"
"    selection-color: rgb(0, 0, 255);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(0, 153, 188);\n"
"}\n"
"")
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(440, 310, 171, 41))
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    border-radius: 20px;\n"
"       font: 14pt \"Fredoka One Light\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(160,160,160);\n"
"    padding: 5px;\n"
"    selection-color: rgb(0, 0, 255);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(0, 153, 188);\n"
"}\n"
"")
        self.lineEdit_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(440, 70, 171, 41))
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    border-radius: 20px;\n"
"       font: 14pt \"Fredoka One Light\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(160,160,160);\n"
"    padding: 5px;\n"
"    selection-color: rgb(0, 0, 255);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(0, 153, 188);\n"
"}\n"
" QToolTip{ border: 1px solid white; background-color:grey ; color: black ; font: 12pt}")
        self.lineEdit_4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(130, 70, 171, 41))
        self.lineEdit_5.setToolTipDuration(-1)
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"    border-radius: 20px;\n"
"       font: 14pt \"Fredoka One Light\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(160,160,160);\n"
"    padding: 5px;\n"
"    selection-color: rgb(0, 0, 255);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(0, 153, 188);\n"
"}\n"
" QToolTip{ border: 1px solid white; background-color:grey ; color: black ; font: 12pt}\n"
"")
        self.lineEdit_5.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(130, 150, 171, 41))
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
"    border-radius: 20px;\n"
"       font: 14pt \"Fredoka One Light\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(160,160,160);\n"
"    padding: 5px;\n"
"    selection-color: rgb(0, 0, 255);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(0, 153, 188);\n"
"}\n"
" QToolTip{ border: 1px solid white; background-color:grey ; color: black ; font: 12pt}")
        self.lineEdit_6.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(130, 230, 171, 41))
        self.lineEdit_7.setStyleSheet("QLineEdit {\n"
"    border-radius: 20px;\n"
"       font: 14pt \"Fredoka One Light\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(160,160,160);\n"
"    padding: 5px;\n"
"    selection-color: rgb(0, 0, 255);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(0, 153, 188);\n"
"}\n"
" QToolTip{ border: 1px solid white; background-color:grey ; color: black ; font: 12pt}")
        self.lineEdit_7.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.lineEdit_7.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_7.setClearButtonEnabled(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(130, 310, 171, 41))
        self.lineEdit_8.setStyleSheet("QLineEdit {\n"
"    border-radius: 20px;\n"
"       font: 14pt \"Fredoka One Light\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(160,160,160);\n"
"    padding: 5px;\n"
"    selection-color: rgb(0, 0, 255);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(0, 153, 188);\n"
"}\n"
" QToolTip{ border: 1px solid white; background-color:grey ; color: black ; font: 12pt}")
        self.lineEdit_8.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_8.setClearButtonEnabled(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(230, 390, 161, 41))
        self.pushButton.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Fredoka One \";\n"
"border: 2px solid rgb(160,160,160);\n"
"padding: 5px;\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"   \n"
"    background-color: rgb(0, 85, 255);\n"
"    \n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        MainWindow2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 622, 21))
        self.menubar.setObjectName("menubar")
        MainWindow2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow2)
        self.statusbar.setObjectName("statusbar")
        MainWindow2.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "MainWindow"))
        self.label.setText(_translate("MainWindow2", "Registration"))
        self.label_2.setText(_translate("MainWindow2", "Name"))
        self.label_3.setText(_translate("MainWindow2", "Username"))
        self.label_4.setToolTip(_translate("MainWindow2", "<html><head/><body><p>DD/MM/YY format </p></body></html>"))
        self.label_4.setText(_translate("MainWindow2", "DOB (DD/MM/YY)"))
        self.label_5.setText(_translate("MainWindow2", "Password"))
        self.label_6.setText(_translate("MainWindow2", "<html><head/><body><p>Money to</p><p>deposit</p></body></html>"))
        self.label_7.setText(_translate("MainWindow2", "Address"))
        self.label_8.setText(_translate("MainWindow2", "Phone no."))
        self.label_9.setText(_translate("MainWindow2", "Aadhar no."))
        self.lineEdit_4.setToolTip(_translate("MainWindow2", "<html><head/><body><p>DD/MM/YY format</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow2", "Login"))
        self.pushButton.clicked.connect(self.registre)
        '''self.lineEdit.setText('hi')
        self.lineEdit_2.setText('hi')
        self.lineEdit_3.setText('hi')
        self.lineEdit_4.setText('hi')
        self.lineEdit_5.setText('hi')
        self.lineEdit_6.setText('hi')
        self.lineEdit_7.setText('hi')'''
        #self.lineEdit_8.setText('hi')





    def registre(self):
        import datetime as date
        SpecialSym =['$', '@', '#', '%']
        a='.'
        a1='#'
        a2='$'
        a3='*'
        a4='&'
        a5='='
        a6=','
        a7='@'
        a8='?'
        a9='/'
        ut= self.lineEdit.text()
        ut1=self.lineEdit_2.text()
        z=self.lineEdit_3.text()
        ut2= self.lineEdit_4.text()
        ut3= self.lineEdit_5.text()
        ut4= self.lineEdit_6.text()
        ut5= self.lineEdit_7.text()
        ut6 = self.lineEdit_8.text()
        

        msg2=QtWidgets.QMessageBox()
        msg2.setText('Password should contain atleast 6 characters, a number , an Upper key letter, a lower key letter and a special character')
        
        if (a in ut3) or (a1 in ut3) or (a3 in ut3) or (a4 in ut3) or (a5 in ut3) or (a6 in ut3) or (a7 in ut3) or (a8 in ut3) or (a9 in ut3):
            msg=QtWidgets.QMessageBox()
            msg.setText('Special Characters in name not allowed')
            msg.exec_()
        elif (a in ut4) or (a1 in ut4) or (a3 in ut4) or (a4 in ut4) or (a5 in ut4) or (a6 in ut4) or (a7 in ut4) or (a8 in ut4) or (a9 in ut4):
            msg1=QtWidgets.QMessageBox()
            msg1.setText('Special Characters in name not allowed')
            msg1.exec_()
        elif (len(ut5)<6):
            msg2.exec_()
        elif not any(char.isdigit() for char in ut5):
            msg2.exec_()
        elif not any(char.isupper() for char in ut5):
            msg2.exec_()
        elif not any(char.islower() for char in ut5):
            msg2.exec_()
        elif not any(char in SpecialSym for char in ut5 ):
            msg2.exec_()

        elif (ut6.isalpha()):
            msg3=QtWidgets.QMessageBox()
            msg3.setText('Enter valid amount to deposit')
            msg3.exec_()

        elif (ut2!=''):
            try:
                    a = date.datetime.strptime(ut2, "%Y-%m-%d").date()
            except :
        
                msg4=QtWidgets.QMessageBox()
                msg4.setText('Enter DOB in DD/MM/YY format')
                msg4.exec_()
            
        elif (len(ut1)!=10) or (ut1.isalpha()):
            
            msg5=QtWidgets.QMessageBox()
            msg5.setText('Enter valid Phone no.')
            msg5.exec_()
        elif (len(z)!=12) or (z.isalpha()):
            
            msg6=QtWidgets.QMessageBox()
            msg6.setText('Enter valid Aadhar no.')
            msg6.exec_()
        
        print('hi')
        q="insert into bank values('{}','{}','{}','{}','{}','{}','{}','{}')".format(ut3,ut4,ut5,ut2,ut,ut1,z,ut6)
        mycur.execute(q)
        mycon.commit()
        msg7=QtWidgets.QMessageBox()
        msg7.setText('Registration successful')
        msg7.exec_()
        
        from bank import Ui_MainWindow
        self.window3 = QtWidgets.QMainWindow()
        self.ui3 = Ui_MainWindow()
        self.ui3.setupUi(self.window3)
        self.window3.show()

        MainWindow2.close()
        
       
            
        
        
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow2 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow2)
    MainWindow2.show()
    sys.exit(app.exec_())
